port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: SG1
    server: ava.game.naver.com
    port: 443
    type: vmess
    uuid: 6523c535-d167-4cd1-9c7d-7fa8a3620787
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dor.bist.biz.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: dor.bist.biz.id
    udp: true
  - name: SG2
    server: df.game.naver.com
    port: 443
    type: vmess
    uuid: 6523c535-d167-4cd1-9c7d-7fa8a3620787
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dor.bist.biz.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: dor.bist.biz.id
    udp: true
  - name: SG3
    server: account.pmang.game.naver.com
    port: 443
    type: vmess
    uuid: 6523c535-d167-4cd1-9c7d-7fa8a3620787
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dor.bist.biz.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: dor.bist.biz.id
    udp: true
  - name: SG4
    server: care.pmang.game.naver.com
    port: 443
    type: vmess
    uuid: 6523c535-d167-4cd1-9c7d-7fa8a3620787
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dor.bist.biz.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: dor.bist.biz.id
    udp: true
  - name: SG5
    server: investor.fb.com
    port: 443
    type: vmess
    uuid: 6523c535-d167-4cd1-9c7d-7fa8a3620787
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dor.bist.biz.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: dor.bist.biz.id
    udp: true
  - name: SG6
    server: investor.mt.com
    port: 443
    type: vmess
    uuid: 6523c535-d167-4cd1-9c7d-7fa8a3620787
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dor.bist.biz.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: dor.bist.biz.id
    udp: true
  - name: SG7
    server: investor.atmeta.com
    port: 443
    type: vmess
    uuid: 6523c535-d167-4cd1-9c7d-7fa8a3620787
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dor.bist.biz.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: dor.bist.biz.id
    udp: true

proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AKUN1
      - AKUN2
      - AKUN3

  - name: SG-X
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SG1
      - SG2
      - SG3
      - SG4
      - SG5
      - SG6
      - SG7
     
      
  - name: IKLAN
    type: select
    proxies:
     - SG-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,SG-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,SG-X
 - RULE-SET,Streaming,SG-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,SG-X
 - RULE-SET,Meta,SG-X
 - RULE-SET,PortGame,GAME
 - MATCH,SG-X


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  
